// nad-master-fn is a KRM function that controls how NetworkAttachmentDefinition
// (NAD) "master" fields are set, supporting two networking modes:
//
//   - networking-mode: "nic" (default)
//     Replaces the macvlan "master" field in each NAD's spec.config JSON
//     with a physical NIC name, bypassing Nephio's VLAN layer entirely.
//     Pods attach directly to the physical interface (e.g. ens1f0).
//
//   - networking-mode: "vlan"
//     Leaves the NADs untouched. Nephio's native flow stands:
//     Interface (attachmentType: vlan) -> VLANClaim (vlan-specializer) ->
//     nad-fn renders master: <masterInterface>.<vlanID> (e.g. ens4f0.6).
//     The vlan-agent DaemonSet (networking/vlan-agent package) creates the
//     VLAN sub-interfaces on the nodes automatically.
//
// In "nic" mode it reads interface-to-NIC mappings from the functionConfig
// (ConfigMap), identifies each NAD by its specializer.nephio.org/owner
// annotation, parses the spec.config JSON properly, replaces only the
// "master" field, and serializes clean JSON back — preserving all other
// fields (mode, ipam, tuning).
//
// Usage in Kptfile:
//
//	pipeline:
//	  mutators:
//	    - image: docker.io/rehanfazal47/nad-master-fn:v2.0
//	      configPath: interface-setters.yaml
//
// Usage in PackageVariant:
//
//	pipeline:
//	  mutators:
//	    - image: docker.io/rehanfazal47/nad-master-fn:v2.0
//	      configMap:
//	        networking-mode: nic
//	        n3-interface: ens1f0
//	        n4-interface: eno49
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if err := Process(os.Stdin, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

// Process reads a kpt ResourceList from r and writes the mutated list to w.
func Process(r io.Reader, w io.Writer) error {
	// Read the full ResourceList YAML from stdin
	input, err := io.ReadAll(r)
	if err != nil {
		return fmt.Errorf("reading stdin: %w", err)
	}

	// Parse as yaml.Node tree (preserves all structure, comments, ordering)
	var doc yaml.Node
	if err := yaml.Unmarshal(input, &doc); err != nil {
		return fmt.Errorf("parsing YAML: %w", err)
	}

	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return fmt.Errorf("expected a YAML document")
	}
	root := doc.Content[0] // root mapping of ResourceList

	// ── Step 0: Determine the networking mode ────────────────────────
	// "nic"  (default): replace NAD masters with physical NIC names
	// "vlan": leave NADs untouched — keep Nephio's native
	//         <masterInterface>.<vlanID> masters generated by nad-fn
	mode := extractNetworkingMode(root)
	switch mode {
	case "vlan":
		appendResults(root, []resultEntry{{
			Message:  "networking-mode=vlan: NAD masters left as generated by nad-fn (native Nephio VLAN flow); ensure the vlan-agent is deployed on the workload cluster",
			Severity: "info",
		}})
		return writeOutput(&doc, w)
	case "", "nic":
		// fall through to NIC replacement below
	default:
		return fmt.Errorf("invalid networking-mode %q: must be \"nic\" or \"vlan\"", mode)
	}

	// ── Step 1: Extract NIC mappings from functionConfig.data ────────
	nicMap := extractNICMappings(root)
	if len(nicMap) == 0 {
		// No mappings provided — pass everything through unchanged
		return writeOutput(&doc, w)
	}

	// ── Step 2: Process items — find NADs and replace master ─────────
	var results []resultEntry
	itemsNode := findValue(root, "items")
	if itemsNode != nil && itemsNode.Kind == yaml.SequenceNode {
		for _, item := range itemsNode.Content {
			if item.Kind == yaml.MappingNode {
				if msg := processNAD(item, nicMap); msg != "" {
					results = append(results, resultEntry{
						Message:  msg,
						Severity: "info",
					})
				}
			}
		}
	}

	// ── Step 3: Append results to ResourceList ───────────────────────
	appendResults(root, results)

	// ── Step 4: Write modified ResourceList to stdout ────────────────
	return writeOutput(&doc, w)
}

// ═══════════════════════════════════════════════════════════════════════
// Core Logic
// ═══════════════════════════════════════════════════════════════════════

// processNAD checks if an item is a NAD and replaces the macvlan master field.
// Returns a message string if a replacement was made, empty string otherwise.
func processNAD(item *yaml.Node, nicMap map[string]string) string {
	// Only process NetworkAttachmentDefinition resources
	kind := getScalar(item, "kind")
	if kind != "NetworkAttachmentDefinition" {
		return ""
	}

	// Get the interface name from the owner annotation
	// e.g. "req.nephio.org/v1alpha1.Interface.n3" → "n3"
	metadata := findValue(item, "metadata")
	if metadata == nil {
		return ""
	}
	annotations := findValue(metadata, "annotations")
	if annotations == nil {
		return ""
	}
	owner := getAnnotationValue(annotations, "specializer.nephio.org/owner")
	ifName := extractInterfaceName(owner)
	if ifName == "" {
		return ""
	}

	// Look up the desired NIC for this interface
	nicKey := ifName + "-interface" // e.g. "n3-interface"
	desiredNIC, exists := nicMap[nicKey]
	if !exists {
		return "" // no mapping for this interface — leave unchanged
	}

	// Get spec.config (the JSON string inside the NAD)
	spec := findValue(item, "spec")
	if spec == nil {
		return ""
	}
	configNode := findValueNode(spec, "config")
	if configNode == nil || configNode.Kind != yaml.ScalarNode {
		return ""
	}

	configStr := configNode.Value

	// Parse the NAD config as JSON
	var config map[string]interface{}
	if err := json.Unmarshal([]byte(configStr), &config); err != nil {
		return fmt.Sprintf("warning: could not parse NAD config JSON: %v", err)
	}

	// Find the macvlan plugin and replace its "master" field
	plugins, ok := config["plugins"].([]interface{})
	if !ok {
		return ""
	}

	modified := false
	for i, p := range plugins {
		pluginMap, ok := p.(map[string]interface{})
		if !ok {
			continue
		}
		if pluginMap["type"] == "macvlan" {
			pluginMap["master"] = desiredNIC
			plugins[i] = pluginMap
			modified = true
		}
	}

	if !modified {
		return ""
	}

	config["plugins"] = plugins

	// Serialize the modified JSON back
	newJSON, err := json.Marshal(config)
	if err != nil {
		return fmt.Sprintf("warning: could not marshal NAD config: %v", err)
	}

	// Write the new JSON string back to spec.config
	configNode.Value = string(newJSON)
	configNode.Tag = "!!str"
	configNode.Style = 0 // let the encoder decide formatting

	nadName := getScalar(metadata, "name")
	return fmt.Sprintf("set master=%q for NAD %s (interface %s)", desiredNIC, nadName, ifName)
}

// ═══════════════════════════════════════════════════════════════════════
// NIC Mapping Extraction
// ═══════════════════════════════════════════════════════════════════════

// extractNetworkingMode reads functionConfig.data["networking-mode"].
// Returns "" when the key is absent (treated as "nic" for backward
// compatibility with v1.0 configs).
func extractNetworkingMode(root *yaml.Node) string {
	fc := findValue(root, "functionConfig")
	if fc == nil {
		return ""
	}
	data := findValue(fc, "data")
	if data == nil || data.Kind != yaml.MappingNode {
		return ""
	}
	for i := 0; i < len(data.Content)-1; i += 2 {
		if data.Content[i].Value == "networking-mode" {
			return strings.TrimSpace(data.Content[i+1].Value)
		}
	}
	return ""
}

// extractNICMappings reads functionConfig.data and returns a map of
// interface keys to NIC names.
// e.g. {"n3-interface": "ens1f0", "n4-interface": "eno49"}
func extractNICMappings(root *yaml.Node) map[string]string {
	nicMap := make(map[string]string)

	fc := findValue(root, "functionConfig")
	if fc == nil {
		return nicMap
	}

	data := findValue(fc, "data")
	if data == nil || data.Kind != yaml.MappingNode {
		return nicMap
	}

	for i := 0; i < len(data.Content)-1; i += 2 {
		key := data.Content[i].Value
		val := strings.TrimSpace(data.Content[i+1].Value)
		if strings.HasSuffix(key, "-interface") && val != "" {
			nicMap[key] = val
		}
	}
	return nicMap
}

// ═══════════════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════════════

// extractInterfaceName gets the interface name from the owner annotation.
// "req.nephio.org/v1alpha1.Interface.n3" → "n3"
func extractInterfaceName(owner string) string {
	if owner == "" {
		return ""
	}
	parts := strings.Split(owner, ".")
	if len(parts) < 2 {
		return ""
	}
	// Verify it's an Interface resource
	if parts[len(parts)-2] != "Interface" {
		return ""
	}
	return parts[len(parts)-1]
}

// findValue finds the value node for a given key in a mapping node.
func findValue(mapping *yaml.Node, key string) *yaml.Node {
	if mapping == nil || mapping.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i < len(mapping.Content)-1; i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

// findValueNode is the same as findValue — returns the value node for a key.
func findValueNode(mapping *yaml.Node, key string) *yaml.Node {
	return findValue(mapping, key)
}

// getScalar traverses nested mappings to get a scalar value.
// e.g. getScalar(item, "kind") or getScalar(item, "metadata", "name")
func getScalar(node *yaml.Node, keys ...string) string {
	current := node
	for _, key := range keys {
		current = findValue(current, key)
		if current == nil {
			return ""
		}
	}
	if current.Kind == yaml.ScalarNode {
		return current.Value
	}
	return ""
}

// getAnnotationValue finds an annotation value in an annotations mapping node.
// Handles annotation keys that may contain dots and slashes.
func getAnnotationValue(annotations *yaml.Node, key string) string {
	if annotations == nil || annotations.Kind != yaml.MappingNode {
		return ""
	}
	for i := 0; i < len(annotations.Content)-1; i += 2 {
		if annotations.Content[i].Value == key {
			return annotations.Content[i+1].Value
		}
	}
	return ""
}

// ═══════════════════════════════════════════════════════════════════════
// Results & Output
// ═══════════════════════════════════════════════════════════════════════

type resultEntry struct {
	Message  string
	Severity string
}

// appendResults adds result entries to the ResourceList for pipeline logging.
func appendResults(root *yaml.Node, results []resultEntry) {
	if len(results) == 0 {
		return
	}

	// Build the results sequence node
	resultsSeq := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, r := range results {
		entry := &yaml.Node{
			Kind: yaml.MappingNode,
			Tag:  "!!map",
			Content: []*yaml.Node{
				{Kind: yaml.ScalarNode, Value: "message", Tag: "!!str"},
				{Kind: yaml.ScalarNode, Value: r.Message, Tag: "!!str"},
				{Kind: yaml.ScalarNode, Value: "severity", Tag: "!!str"},
				{Kind: yaml.ScalarNode, Value: r.Severity, Tag: "!!str"},
			},
		}
		resultsSeq.Content = append(resultsSeq.Content, entry)
	}

	// Append or replace "results" in root
	for i := 0; i < len(root.Content)-1; i += 2 {
		if root.Content[i].Value == "results" {
			root.Content[i+1] = resultsSeq
			return
		}
	}
	// Key doesn't exist — append it
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "results", Tag: "!!str"},
		resultsSeq,
	)
}

// writeOutput encodes the document to the provided writer.
func writeOutput(doc *yaml.Node, w io.Writer) error {
	enc := yaml.NewEncoder(w)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return fmt.Errorf("encoding output: %w", err)
	}
	return enc.Close()
}
