# Defines CNI type and master interface for macvlan/VLAN traffic
# WorkloadCluster CR for the SD-Core cluster

apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: core
  labels:
    nephio.org/cluster-type: core
    nephio.org/site: core
spec:
  clusterName: core
  cnis:
  - macvlan
  masterInterface: ens3