# Multus CNI PackageVariant for Core cluster
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: multus-core
spec:
  upstream:
    repo: nephio-workload-blueprints
    package: networking/multus-cni
  downstream:
    repo: core
    package: multus-cni
  annotations:
    approval.nephio.org/policy: always
  pipeline:
    mutators:
      - image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
        configMap:
          cluster-name: core